
import { CTQuestion } from '../../types';

export const P4_QUESTIONS: CTQuestion[] = [
  {
    id: 'm7-p4-q1',
    number: 1,
    temaPrincipal: 'Diferenciação Sexual Humana',
    topicoEspecifico: 'Cascatas Moleculares (Gene SRY)',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'Identificado em 1990, o gene SRY é considerado o principal determinante genético do sexo masculino. Qual é o seu principal alvo transcricional imediato para iniciar a diferenciação testicular na crista gonadal?',
    alternativas: ['WNT4.', 'FOXL2.', 'SOX9.', 'DAX1.', 'RSPO1.'],
    gabarito: 2,
    comentario: 'O SOX9 é o efetor central. O SRY ativa o SOX9, que por sua vez induz a diferenciação das células de Sertoli e inibe genes pró-ovário (como WNT4).'
  },
  {
    id: 'm7-p4-q2',
    number: 2,
    temaPrincipal: 'Diferenciação Sexual Humana',
    topicoEspecifico: 'Morfogênese Genital (Ductos de Müller)',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'No sexo masculino, a regressão ativa dos ductos de Müller é concluída por volta da 10ª semana de gestação. Qual estrutura celular é a produtora exclusiva do Hormônio Antimülleriano (AMH) responsável por esse processo na vida fetal?',
    alternativas: ['Células de Leydig.', 'Células de Sertoli.', 'Células da teca.', 'Células da granulosa.', 'Células germinativas primordiais.'],
    gabarito: 1,
    comentario: 'As Células de Sertoli fetais produzem AMH (membro da família TGF-beta) para causar a regressão dos ductos de Müller.'
  },
  {
    id: 'm7-p4-q3',
    number: 3,
    temaPrincipal: 'Diferenciação Sexual Humana',
    topicoEspecifico: 'Ação dos Andrógenos (DHT)',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'A diferenciação dos genitais externos masculinos (falo, fusão labioescrotal e próstata) depende da conversão da testosterona em di-hidrotestosterona (DHT). Qual enzima é responsável por essa conversão e em que região o gene correspondente está localizado?',
    alternativas: ['Aromatase; Cromossomo X.', '21-hidroxilase; Cromossomo 6.', '5-alfa-redutase tipo 2; Gene SRD5A2.', '17-beta-hidroxiesteroide desidrogenase; Gene HSD17B3.', 'P450scc; Mitocôndria.'],
    gabarito: 2,
    comentario: 'A 5-alfa-redutase transforma Testosterona em DHT (mais potente). Deficiências aqui causam genitália externa ambígua em indivíduos XY.'
  },
  {
    id: 'm7-p4-q4',
    number: 4,
    temaPrincipal: 'Diferenciação Sexual Humana',
    topicoEspecifico: 'Vias de Diferenciação Ovariana',
    grauImportancia: 'Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'Atualmente, sabe-se que a diferenciação ovariana não é um processo passivo, mas dependente da supressão ativa da via testicular. Qual gene é conhecido como o "guardião da identidade das células da granulosa", suprimindo o SOX9 ao longo de toda a vida adulta?',
    alternativas: ['SRY.', 'DMRT1.', 'FOXL2.', 'FGF9.', 'SF1.'],
    gabarito: 2,
    comentario: 'O FOXL2 é essencial para manter o fenótipo feminino das células da granulosa. Sem ele, mesmo um ovário adulto pode começar a expressar genes testiculares.'
  },
  {
    id: 'm7-p4-q5',
    number: 5,
    temaPrincipal: 'Diferenciação Sexual Humana',
    topicoEspecifico: 'Distúrbios do Desenvolvimento Sexual (DDS)',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'Uma recém-nascida apresenta ambivalência genital com hipertrofia do clitóris e fusão labioescrotal (Grau IV na escala de Prader), mas com genitais internos femininos preservados. O diagnóstico mais provável é Hiperplasia Adrenal Congênita (HAC) por deficiência de qual enzima?',
    alternativas: ['5-alfa-redutase.', '11-beta-hidroxilase.', '21-hidroxilase.', 'Aromatase placentária.', 'AMH sintase.'],
    gabarito: 2,
    comentario: 'A 21-hidroxilase é responsável por >90% dos casos de HAC. Sua falta desvia os precursores para a via dos andrógenos, virilizando fetos XX.'
  },
  {
    id: 'm7-p4-q6',
    number: 6,
    temaPrincipal: 'Período Fetal e Maturação',
    topicoEspecifico: 'Circulação Fetal (Shunts)',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'Na circulação fetal, o sangue oxigenado vindo da placenta deve ser direcionado preferencialmente para o coração e o cérebro. Qual estrutura é responsável por desviar parte desse sangue da veia umbilical diretamente para a veia cava inferior, contornando o fígado?',
    alternativas: ['Forame oval.', 'Ducto arterioso.', 'Ducto venoso.', 'Veia porta.', 'Artéria hipogástrica.'],
    gabarito: 2,
    comentario: 'O Ducto Venoso é um shunt que leva sangue oxigenado da veia umbilical para a VCI, evitando a passagem lenta pelo leito hepático.'
  },
  {
    id: 'm7-p4-q7',
    number: 7,
    temaPrincipal: 'Período Fetal e Maturação',
    topicoEspecifico: 'Desenvolvimento Pulmonar (Fases)',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'O desenvolvimento pulmonar fetal é dividido em cinco fases. Em qual fase ocorre o surgimento dos ácinos, o início da vascularização e a diferenciação dos pneumócitos, sendo o limite crítico para a viabilidade extrauterina (16ª-26ª semana)?',
    alternativas: ['Embrionária.', 'Pseudoglandular.', 'Canalicular.', 'Sacular.', 'Alveolar.'],
    gabarito: 2,
    comentario: 'A fase Canalicular é o divisor de águas da viabilidade, pois é quando surgem os primeiros alvéolos primitivos e o início da barreira alvéolo-capilar.'
  },
  {
    id: 'm7-p4-q8',
    number: 8,
    temaPrincipal: 'Período Fetal e Maturação',
    topicoEspecifico: 'Líquido Amniótico e Função Renal',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'A partir do segundo trimestre, qual é a principal fonte de produção do líquido amniótico?',
    alternativas: ['Secreção pulmonar fetal.', 'Transudação de vasos maternos.', 'Urina fetal.', 'Deglutição fetal.', 'Membranas coriônicas.'],
    gabarito: 2,
    comentario: 'No início, o fluido é ultrafiltrado materno; após a 16ª semana, a Urina Fetal assume o papel principal (fundamental para o desenvolvimento pulmonar).'
  },
  {
    id: 'm7-p4-q9',
    number: 9,
    temaPrincipal: 'Período Fetal e Maturação',
    topicoEspecifico: 'Dinâmica de Crescimento',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'O crescimento fetal possui prioridades distintas conforme o trimestre. Assinale a alternativa que descreve corretamente a dinâmica do terceiro trimestre (28ª semana ao nascimento):',
    alternativas: ['Crescimento linear intenso (comprimento) de 5 cm por mês.', 'Organogênese e formação da estrutura básica dos órgãos.', 'Acúmulo ponderal acelerado e deposição de gordura branca e glicogênio.', 'Fase de maior sensibilidade a agentes teratógenos estruturais.', 'Pico de proliferação neuronal (neurogênese).'],
    gabarito: 2,
    comentario: 'O 3º trimestre é marcado pela deposição de gordura e glicogênio, preparando o feto para a vida térmica e energética extrauterina.'
  },
  {
    id: 'm7-p4-q10',
    number: 10,
    temaPrincipal: 'Período Fetal e Maturação',
    topicoEspecifico: 'Programação Fetal (DOHaD)',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'A Hipótese de Barker (ou DOHaD) propõe que adversidades sofridas durante o período fetal reprogramam o metabolismo. Qual é o impacto clínico dessa programação na vida adulta?',
    alternativas: ['Redução da expectativa de vida por malformações congênitas.', 'Aumento do risco de doenças crônicas como hipertensão, diabetes tipo 2 e obesidade.', 'Imunidade aumentada para doenças infecciosas.', 'Maior estatura final devido à compensação pós-natal.', 'Prevenção de doenças neurodegenerativas.'],
    gabarito: 1,
    comentario: 'A Hipótese de Barker relaciona o baixo peso ao nascer/insultos fetais com o "ajuste" metabólico que predispõe a doenças cardiovasculares no adulto.'
  },
  {
    id: 'm7-p4-q11',
    number: 11,
    temaPrincipal: 'Neurobiologia Gestacional',
    topicoEspecifico: 'Eixo Hipotálamo-Hipófise-Adrenal',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'Ao longo da gestação, os níveis de cortisol materno aumentam progressivamente, podendo triplicar no terceiro trimestre. Embora fisiológico, qual é o impacto desse aumento na saúde mental da gestante?',
    alternativas: ['Promove uma sensação de euforia e energia inesgotável.', 'Contribui para a labilidade emocional e hipersensibilidade ao estresse.', 'Reduz a necessidade de sono da gestante no primeiro trimestre.', 'Impede a ativação de circuitos neurais associados à ansiedade.', 'Melhora significativamente as funções executivas e a memória.'],
    gabarito: 1,
    comentario: 'O Cortisol alto (hipercortisolismo fisiológico) mantém a gestante em estado de alerta, mas pode causar fadiga e labilidade emocional intensa.'
  },
  {
    id: 'm7-p4-q12',
    number: 12,
    temaPrincipal: 'Neurobiologia Gestacional',
    topicoEspecifico: 'Ocitocina e Vínculo',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'Qual hormônio, cujos níveis elevam-se ao longo da gestação com picos no parto e amamentação, é responsável por reduzir a resposta ao estresse e facilitar a formação do vínculo afetivo materno-fetal?',
    alternativas: ['Cortisol.', 'Estrogênio.', 'Ocitocina.', 'Prolactina.', 'Testosterona.'],
    gabarito: 2,
    comentario: 'A Ocitocina é o "hormônio do amor e do vínculo", agindo para reduzir a ansiedade e promover o comportamento de cuidado.'
  },
  {
    id: 'm7-p4-q13',
    number: 13,
    temaPrincipal: 'Psicologia da Gestação',
    topicoEspecifico: 'Representações do Bebê (Daniel Stern)',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'Segundo Daniel Stern, a gestante constrói representações mentais do filho. Como é chamado o ser concreto, com temperamento próprio, ao qual a mãe deve se adaptar no pós-parto, substituindo a representação idealizada?',
    alternativas: ['Bebê Fantasmático.', 'Bebê Imaginário.', 'Bebê Real.', 'Bebê Simbólico.', 'Bebê de Substituição.'],
    gabarito: 2,
    comentario: 'O Bebê Real é aquele que nasce com características próprias, exigindo que a mãe abandone as fantasias do "Bebê Imaginário" para se conectar com o indivíduo real.'
  },
  {
    id: 'm7-p4-q14',
    number: 14,
    temaPrincipal: 'Psicologia da Gestação',
    topicoEspecifico: 'Baby Blues vs Depressão Pós-Parto',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'O "baby blues" é um período de labilidade emocional que acomete até 80% das puérperas. Sobre essa condição, é correto afirmar:',
    alternativas: ['É um transtorno grave que requer internação psiquiátrica imediata.', 'Tem início tardio, geralmente após o primeiro mês do nascimento.', 'É autolimitado, com duração típica de até 2 semanas pós-parto.', 'Ocorre principalmente pela falta de suporte do parceiro.', 'É causado pelo excesso de ocitocina circulante no puerpério.'],
    gabarito: 2,
    comentario: 'O Baby Blues atinge a maioria das mulheres, inicia-se no 3º dia e desaparece em até 14 dias sem necessidade de medicação, apenas apoio.'
  },
  {
    id: 'm7-p4-q15',
    number: 15,
    temaPrincipal: 'Psicologia da Gestação',
    topicoEspecifico: 'Matrescence',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'O termo "Matrescence", cunhado pela antropóloga Dana Raphael, descreve o processo de tornar-se mãe como uma transição desenvolvimental tão profunda quanto a:',
    alternativas: ['Menopausa.', 'Infância.', 'Adolescência.', 'Senescência.', 'Vida adulta.'],
    gabarito: 2,
    comentario: 'A Matrescence é comparada à adolescência pela magnitude das mudanças hormonais, cerebrais e de identidade (transição de "filha" para "mãe").'
  },
  {
    id: 'm7-p4-q16',
    number: 16,
    temaPrincipal: 'Diferenciação Sexual Humana',
    topicoEspecifico: 'Genética do Cromossoma X (Lyonização)',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'Em células somáticas 46,XX, ocorre um processo de silenciamento de um dos cromossomas X para compensação de dose génica. Sobre este fenómeno, assinale a alternativa correta:',
    alternativas: ['É um processo reversível em todas as divisões mitóticas subsequentes.', 'A inativação é aleatória, permanente e ocorre a partir do estágio de blastocisto.', 'Todos os genes do cromossoma X inativado são silenciados, sem exceções.', 'Os genes da região pseudoautossómica também são inativados para garantir a igualdade com o homem.', 'Ocorre apenas no sexo masculino em casos de Síndrome de Klinefelter.'],
    gabarito: 1,
    comentario: 'A Lyonização (Inativação do X) é aleatória em cada célula, mas uma vez feita, todas as células filhas mantêm o mesmo X inativado (permanente).'
  },
  {
    id: 'm7-p4-q17',
    number: 17,
    temaPrincipal: 'Diferenciação Sexual Humana',
    topicoEspecifico: 'Síndrome de Swyer vs. SIA',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'Considere um indivíduo com cariótipo 46,XY que apresenta genitália externa feminina completa, útero e trompas de Falópio presentes, mas com gónadas disgenéticas ("streak gonads"). Qual a explicação molecular correta para este fenótipo?',
    alternativas: ['Mutação no recetor de androgénios (SIA), impedindo a ação da testosterona.', 'Deficiência de 5-alfa-redutase, impedindo a formação de genitais externos masculinos.', 'Mutação de perda de função no gene SRY, resultando em disgenesia gonadal e ausência de produção de AMH e testosterona.', 'Produção excessiva de WNT4 pela adrenal, suprimindo o testículo.', 'Translocação do gene SRY para o cromossoma X.'],
    gabarito: 2,
    comentario: 'Na Síndrome de Swyer, o defeito é na determinação gonadal (SRY). Como não há gônada funcional, não há AMH nem Testosterona; o fenótipo segue o caminho feminino padrão (com útero).'
  },
  {
    id: 'm7-p4-q18',
    number: 18,
    temaPrincipal: 'Diferenciação Sexual Humana',
    topicoEspecifico: 'Disruptores Endócrinos',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'Os ftalatos, plastificantes comuns em cosméticos e PVC, são considerados disruptores endócrinos com impacto no desenvolvimento fetal masculino. Qual é o seu principal mecanismo de interferência documentado?',
    alternativas: ['Indução da aromatase, transformando testosterona em estrogénio.', 'Ação antiandrogénica através da inibição da síntese de testosterona pelas células de Leydig fetais.', 'Bloqueio total da migração das células germinativas primordiais.', 'Mimetismo estrogénico forte que ativa o gene FOXL2 no homem.', 'Inativação permanente do gene SOX9 no cromossoma 17.'],
    gabarito: 1,
    comentario: 'Ftalatos reduzem a expressão de enzimas esteroidogênicas nas Células de Leydig, diminuindo a testosterona fetal (efeito antiandrogênico).'
  },
  {
    id: 'm7-p4-q19',
    number: 19,
    temaPrincipal: 'Período Fetal e Maturação',
    topicoEspecifico: 'Perfil Biofísico Fetal (PBF)',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'O Escore de Manning avalia o bem-estar fetal através de cinco parâmetros. Segundo a padronização clínica, qual o critério para atribuir a pontuação máxima (2 pontos) ao parâmetro "Movimentos Respiratórios Fetais"?',
    alternativas: ['Presença de pelo menos 3 episódios de soluços em 30 minutos.', 'Pelo menos um episódio de respiração contínua com duração de 30 segundos em um período de 30 minutos.', 'Frequência respiratória fetal estável entre 40 e 60 incursões por minuto.', 'Expansão torácica rítmica durante as contrações uterinas.', 'Presença de fluxo de líquido amniótico nas narinas ao Doppler.'],
    gabarito: 1,
    comentario: 'No PBF de Manning, a respiração fetal é pontuada como normal se houver 30 segundos contínuos de movimentos torácicos em 30 minutos.'
  },
  {
    id: 'm7-p4-q20',
    number: 20,
    temaPrincipal: 'Período Fetal e Maturação',
    topicoEspecifico: 'Unidade Fetoplacentária (Estrogénios)',
    grauImportancia: 'Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'A síntese de estrogénios (especialmente o estriol) durante a gestação depende da cooperação metabólica entre o feto e a placenta. Qual órgão fetal fornece os precursores de esteroides necessários para que a placenta realize a aromatização?',
    alternativas: ['Fígado fetal.', 'Pâncreas fetal.', 'Córtex da glândula suprarrenal fetal.', 'Rins fetais via urina.', 'Pulmões fetais via surfactante.'],
    gabarito: 2,
    comentario: 'O feto e a placenta cooperam: a suprarrenal fetal fornece DHEA-S, que a placenta converte em estriol (E3).'
  },
  {
    id: 'm7-p4-q21',
    number: 21,
    temaPrincipal: 'Período Fetal e Maturação',
    topicoEspecifico: 'Maturação Sensorial',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'A maturação dos sentidos fetais segue uma cronologia específica. Qual é o sentido mais precoce a desenvolver-se, com recetores funcionais já na 8ª semana e respostas reflexas ao toque no final do primeiro trimestre?',
    alternativas: ['Visão.', 'Audição.', 'Tato.', 'Olfato.', 'Gustação.'],
    gabarito: 2,
    comentario: 'O Tato é o primeiro sentido: receptores periorais surgem na 7ª-8ª semana.'
  },
  {
    id: 'm7-p4-q22',
    number: 22,
    temaPrincipal: 'Saúde Mental Perinatal',
    topicoEspecifico: 'Prolactina e Resposta ao Estresse',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'Além da produção de leite, a prolactina exerce funções neurológicas cruciais na gestante e puérpera. Qual o seu efeito principal sobre a amígdala cerebral?',
    alternativas: ['Aumenta a reatividade a estímulos de medo para proteção do ninho.', 'Reduz a reatividade da amígdala a estímulos ameaçadores, promovendo efeito ansiolítico.', 'Inibe a síntese de serotonina, causando o "baby blues".', 'Estimula a memória executiva para planeamento do parto.', 'Ativa o sistema dopaminérgico para o comportamento de nidificação.'],
    gabarito: 1,
    comentario: 'A prolactina "acalma" a amígdala, ajudando a puérpera a focar no bebê em vez de se perder em estímulos de medo irrelevantes.'
  },
  {
    id: 'm7-p4-q23',
    number: 23,
    temaPrincipal: 'Saúde Mental Perinatal',
    topicoEspecifico: 'Luto Perinatal (Disenfranchised Grief)',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'O luto após um abortamento espontâneo é frequentemente agravado pela ausência de rituais sociais e pela minimização da perda pela cultura. Como se denomina este fenómeno psicológico associado ao sofrimento prolongado?',
    alternativas: ['Luto Patológico Antecipatório.', '"Luto Disenfranchised" ou luto não reconhecido.', 'Crise Desenvolvimental Catastrófica.', 'Depressão Pós-Parto Tardia.', 'Psicose Reacional Perinatal.'],
    gabarito: 1,
    comentario: 'O luto Disenfranchised (não reconhecido) é o sofrimento que a sociedade ignora (ex: aborto precoce), dificultando a cura da mulher.'
  },
  {
    id: 'm7-p4-q24',
    number: 24,
    temaPrincipal: 'Saúde Mental Perinatal',
    topicoEspecifico: '"Fantasmas no Quarto do Bebê"',
    grauImportancia: 'Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'Selma Fraiberg utilizou a metáfora "fantasmas no quarto do bebê" para descrever:',
    alternativas: ['Alucinações auditivas comuns na psicose puerperal.', 'Representações não elaboradas da história parental (experiências de apego da infância dos pais) que assombram a nova relação mãe-bebê.', 'O medo irracional da morte súbita do lactente no terceiro trimestre.', 'Sonhos vívidos e pesadelos relacionados à tokofobia.', 'A presença física do parceiro que se sente excluído da relação diádica.'],
    gabarito: 1,
    comentario: 'Os "Fantasmas" de Fraiberg são os traumas dos pais que ressurgem na interação com o bebê (ex: uma mãe agredida que se apavora com o choro do filho).'
  },
  {
    id: 'm7-p4-q25',
    number: 25,
    temaPrincipal: 'Pré-Natal Educativo',
    topicoEspecifico: 'Marcos Normativos (Rede Cegonha/PHPN)',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'Segundo o Programa de Humanização do Pré-Natal e Nascimento (PHPN) e as diretrizes da Rede Cegonha no Brasil, qual é o critério de tempo e quantidade mínima de consultas para um pré-natal adequado?',
    alternativas: ['Início antes da 20ª semana e mínimo de 4 consultas.', 'Início antes da 12ª semana e mínimo de 6 consultas.', 'Início em qualquer trimestre com mínimo de 10 consultas.', 'Apenas consultas mensais após a percepção dos movimentos fetais.', 'Mínimo de 8 consultas, independentemente do trimestre de início.'],
    gabarito: 1,
    comentario: 'A meta do MS/PHPN é captação precoce (< 12 semanas) e ao menos 6 consultas para garantir a prevenção de agravos.'
  },
  {
    id: 'm7-p4-q26',
    number: 26,
    temaPrincipal: 'Pré-Natal Educativo',
    topicoEspecifico: 'Violência Doméstica (Rastreio)',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'O rastreio de violência doméstica deve ser sistemático no pré-natal. Qual instrumento validado é recomendado para aplicação em ambiente privado e acolhedor?',
    alternativas: ['Escala de Edimburgo (EPDS).', 'Questionário PHQ-9.', 'Partner Violence Screen ou AAS (Abuse Assessment Screen).', 'Escore de Manning.', 'Escala de Prader.'],
    gabarito: 2,
    comentario: 'O AAS (Abuse Assessment Screen) é a ferramenta padrão-ouro para detectar violência física e sexual de forma direta e ética.'
  },
  {
    id: 'm7-p4-q27',
    number: 27,
    temaPrincipal: 'Pré-Natal Educativo',
    topicoEspecifico: 'Suplementação de Ácido Fólico',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'A suplementação de ácido fólico é uma prioridade educativa do primeiro trimestre. Qual a sua função principal e a dose recomendada no material?',
    alternativas: ['Prevenção de anemia ferropriva; 27 mg/dia.', 'Prevenção de defeitos do tubo neural; 400 a 800 mcg/dia.', 'Aumento da mineralização óssea fetal; 1000 mg/dia.', 'Maturação pulmonar precoce; dose única de betametasona.', 'Tratamento de náuseas e vómitos; dose variável.'],
    gabarito: 1,
    comentario: 'O Ácido Fólico (B9) é crucial para o fechamento do tubo neural (ocorre até a 4ª semana após a concepção).'
  },
  {
    id: 'm7-p4-q28',
    number: 28,
    temaPrincipal: 'Diferenciação Sexual Humana',
    topicoEspecifico: 'Diferenciação Cerebral e Aromatização',
    grauImportancia: 'Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'Embora a testosterona seja o principal androgénio circulante no feto masculino, a "masculinização" de certos circuitos neuronais no hipotálamo (dimorfismo sexual) depende de um processo paradoxal. Qual é esse processo?',
    alternativas: ['Inibição direta dos recetores de estrogénio pela proteína SRY.', 'Aromatização da testosterona em estradiol dentro dos neurónios alvo no cérebro.', 'Inativação do cromossoma X apenas nas células gliais.', 'Secreção de progesterona pelas glândulas suprarrenais fetais.', 'Ação exclusiva da di-hidrotestosterona (DHT) sem necessidade de receptores nucleares.'],
    gabarito: 1,
    comentario: 'No cérebro masculino, a testosterona sofre aromatização para estradiol, que paradoxalmente "masculiniza" os núcleos hipotalâmicos.'
  },
  {
    id: 'm7-p4-q29',
    number: 29,
    temaPrincipal: 'Diferenciação Sexual Humana',
    topicoEspecifico: 'Identidade de Género vs. Sexo Biológico',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'A diferenciação da identidade de género é um processo complexo que ocorre em janelas temporais distintas da diferenciação genital. De acordo com o material, qual a principal influência na formação da identidade de género?',
    alternativas: ['Apenas o cariótipo (46,XX ou 46,XY).', 'Exclusivamente o ambiente social e a educação pós-natal.', 'Uma interação multifatorial entre a organização hormonal pré-natal do cérebro e fatores psicossociais/culturais.', 'A presença ou ausência de útero.', 'O nível de oxitocina durante o parto.'],
    gabarito: 2,
    comentario: 'A diferenciação da identidade de género é um processo complexo que envolve uma interação multifatorial entre a organização hormonal pré-natal do cérebro e fatores psicossociais/culturais.'
  },
  {
    id: 'm7-p4-q30',
    number: 30,
    temaPrincipal: 'Período Fetal e Maturação',
    topicoEspecifico: 'Proteção Tegumentar (Vernix e Lanugo)',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'Por volta da 20ª semana, o feto é coberto por uma substância esbranquiçada e gordurosa e por pelos finos. Qual a função primordial do vernix caseosa e do lanugo?',
    alternativas: ['Produção de vitamina D a partir do líquido amniótico.', 'Proteção da pele fetal contra a maceração pelo líquido amniótico e auxílio na termorregulação.', 'Estimulação da descida testicular via tração mecânica.', 'Armazenamento de ferro para o período neonatal.', 'Impedir a deglutição de líquido amniótico pelo feto.'],
    gabarito: 1,
    comentario: 'Proteção da pele fetal contra a maceração pelo líquido amniótico e auxílio na termorregulação.'
  },
  {
    id: 'm7-p4-q31',
    number: 31,
    temaPrincipal: 'Período Fetal e Maturação',
    topicoEspecifico: 'Prematuridade e Corticoterapia',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'Em situações de risco iminente de parto prematuro (entre 24 e 34 semanas), a administração de corticosteroides (betametasona ou dexametasona) à gestante é uma intervenção padrão. Qual o objetivo biológico desta ação?',
    alternativas: ['Aumentar o peso fetal para atingir 2500g.', 'Acelerar a produção de surfactante pelos pneumócitos tipo II, reduzindo o risco de Síndrome de Angústia Respiratória.', 'Fechar precocemente o ducto arterioso.', 'Induzir a mielinização acelerada do nervo ótico.', 'Prevenir a icterícia neonatal por maturação hepática.'],
    gabarito: 1,
    comentario: 'Acelerar a produção de surfactante pelos pneumócitos tipo II, reduzindo o risco de Síndrome de Angústia Respiratória.'
  },
  {
    id: 'm7-p4-q32',
    number: 32,
    temaPrincipal: 'Pré-Natal Educativo',
    topicoEspecifico: 'Fisiologia da Lactação (Reflexo de Ejeção)',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'O sucesso da amamentação depende de dois reflexos hormonais principais. Qual hormona é responsável pela ejeção do leite através da contração das células mioepiteliais dos alvéolos mamários em resposta à sucção (ou estímulos emocionais)?',
    alternativas: ['Prolactina.', 'Progesterona.', 'Ocitocina.', 'Estrogénio.', 'Inibina.'],
    gabarito: 2,
    comentario: 'Sucção -> Hipotálamo -> Neuro-hipófise -> Ocitocina -> Contração mioepitelial -> Ejeção. (Diferente da Prolactina, que faz a produção).'
  },
  {
    id: 'm7-p4-q33',
    number: 33,
    temaPrincipal: 'Pré-Natal Educativo',
    topicoEspecifico: 'Colostro vs. Leite Maduro',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'O colostro, secretado nos primeiros dias após o parto, é frequentemente chamado de "a primeira vacina". Qual a característica que justifica este título?',
    alternativas: ['Elevada concentração de lactose para energia imediata.', 'Alta densidade de gordura saturada para ganho de peso.', 'Riqueza em anticorpos (principalmente IgA secretora) e células de defesa (leucócitos).', 'Baixo volume, o que impede a sobrecarga renal do recém-nascido.', 'Presença de ferro em doses terapêuticas.'],
    gabarito: 2,
    comentario: 'O colostro tem menos gordura que o leite maduro, mas é um concentrado de IgA e leucócitos, protegendo o intestino do recém-nascido.'
  },
  {
    id: 'm7-p4-q34',
    number: 34,
    temaPrincipal: 'Pré-Natal Educativo',
    topicoEspecifico: 'Grupos de Gestantes (Pedagogia Freireana)',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'A utilização de grupos de gestantes como estratégia educativa deve basear-se na "educação dialógica". Segundo os conceitos de Paulo Freire aplicados ao pré-natal, o papel do profissional de saúde é:',
    alternativas: ['Transmitir todo o conhecimento técnico de forma unilateral para garantir a obediência.', 'Atuar como facilitador do diálogo, valorizando o saber prévio da gestante e construindo conhecimento coletivamente.', 'Punir comportamentos de risco através de advertências formais.', 'Delegar a educação apenas para materiais impressos (folhetos).', 'Focar exclusivamente nos aspetos biológicos, ignorando aspetos sociais.'],
    gabarito: 1,
    comentario: 'Na pedagogia Freireana, o profissional não é o dono da verdade, mas um facilitador que constrói o plano de parto junto com a família.'
  },
  {
    id: 'm7-p4-q35',
    number: 35,
    temaPrincipal: 'Pré-Natal Educativo',
    topicoEspecifico: 'Avaliação da Qualidade (Donabedian)',
    grauImportancia: 'Baixo',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'Na avaliação da qualidade do cuidado pré-natal, utiliza-se frequentemente a tríade de Donabedian. Se um gestor analisa a "disponibilidade de aparelhos de sonar e a adequação da sala de espera", ele está a avaliar qual dimensão?',
    alternativas: ['Processo.', 'Resultado.', 'Estrutura.', 'Eficácia.', 'Impacto Social.'],
    gabarito: 2,
    comentario: 'Equipamentos e recursos humanos são Estrutura. O modo como a consulta é feita é Processo. O desfecho (mãe e bebê saudáveis) é Resultado.'
  }
];
