import { CTQuestion } from '../../types';

export const P3_QUESTIONS: CTQuestion[] = [
  {
    id: 'm7-p3-q1',
    number: 1,
    temaPrincipal: 'Mecanismos Moleculares do Desenvolvimento',
    topicoEspecifico: 'Indução e Sinalização',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'Durante o desenvolvimento embrionário, a sinalização por BMP4 (Proteína Morfogenética Óssea 4) é fundamental para a especificação do eixo dorsoventral. No entanto, para que o ectoderma se diferencie em tecido neural (neuralização), a ação do BMP4 deve ser bloqueada na região dorsal. Quais são os principais antagonistas secretados pelo nó primitivo e notocorda que realizam esse bloqueio?',
    alternativas: ['Shh (Sonic Hedgehog) e Ácido Retinoico.', 'Noggin, Chordin e Follistatin.', 'Wnt3a e FGF8.', 'TGF-beta e Activina.', 'Epinefrina e Acetilcolina.'],
    gabarito: 1,
    comentario: `● Por que está certa: O ectoderma tem uma tendência intrínseca a tornar-se tecido neural. O BMP4 "empurra" o ectoderma para se tornar epiderme. Noggin, Chordin e Follistatin bloqueiam o BMP4, permitindo que o ectoderma dorsal siga sua via padrão e se torne placa neural.`
  },
  {
    id: 'm7-p3-q2',
    number: 2,
    temaPrincipal: 'Anexos Embrionários',
    topicoEspecifico: 'Placentação e Circulação Uteroplacentária',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'A pré-eclampsia é uma patologia grave da gestação cuja origem está ligada a uma falha na segunda onda de invasão trofoblástica. Qual alteração vascular específica caracteriza essa falha?',
    alternativas: ['Dilatação excessiva das veias uterinas.', 'Persistência da camada muscular e da alta resistência nas artérias espirais.', 'Invasão excessiva do miométrio pelo citotrofoblasto (placenta acreta).', 'Ruptura prematura das artérias umbilicais.', 'Formação de fístulas arteriovenosas no vilo corial.'],
    gabarito: 1,
    comentario: `● Por que está certa: Na gestação normal, o trofoblasto destrói a camada muscular das artérias espirais, transformando-as em vasos de baixa resistência e alto fluxo. Na pré-eclampsia, essa invasão é incompleta, mantendo os vasos estreitos e com alta resistência, gerando isquemia placentária.`
  },
  {
    id: 'm7-p3-q3',
    number: 3,
    temaPrincipal: 'Sistema Urogenital',
    topicoEspecifico: 'Síndrome de Insensibilidade aos Andrógenos (SIA)',
    grauImportancia: 'Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'Indivíduo com cariótipo 46,XY apresenta fenótipo feminino, vagina curta em fundo cego, ausência de útero e gónadas (testículos) intra-abdominais. Os níveis de testosterona são de padrão masculino. Qual a falha fisiológica básica?',
    alternativas: ['Ausência do gene SRY.', 'Deficiência na enzima 5-alfa-redutase.', 'Mutação no recetor de andrógenos, impedindo a ação da testosterona e DHT nos tecidos alvo.', 'Produção excessiva de estrogénio pelas adrenais.', 'Persistência dos ductos de Müller por falta de AMH.'],
    gabarito: 2,
    comentario: `● Por que está certa: Na SIA (antigamente chamada de Feminilização Testicular), o corpo produz testosterona, mas o recetor é "surdo". O fenótipo é feminino porque o corpo converte a testosterona em estrogénio (aromatização periférica), mas não há útero porque o AMH (que não depende do recetor de androgênio) funcionou normalmente.`
  },
  {
    id: 'm7-p3-q4',
    number: 4,
    temaPrincipal: 'Sistema Cardiovascular',
    topicoEspecifico: 'Cardiopatias Congênitas (Conotruncal)',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'A Tetralogia de Fallot é a cardiopatia cianótica mais comum. Sua patogênese está ligada a uma única alteração embriológica que gera os quatro componentes da malformação. Qual é essa alteração?',
    alternativas: ['Falha no fechamento do forame oval.', 'Desvio anterior e superior do septo infundibular (conotruncal).', 'Persistência do ducto arterioso.', 'Inversão da posição dos grandes vasos.', 'Atresia da válvula tricúspide.'],
    gabarito: 1,
    comentario: `● Por que está certa: O desvio anterior do septo conotruncal causa: 1) Estenose pulmonar; 2) Comunicação Interventricular (CIV); 3) Dextroposição da aorta (cavalga a CIV); 4) Hipertrofia do ventrículo direito (consequência da pressão alta).`
  },
  {
    id: 'm7-p3-q5',
    number: 5,
    temaPrincipal: 'Desenvolvimento Pulmonar',
    topicoEspecifico: 'Surfactante e Maturidade Fetal',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'A Síndrome do Desconforto Respiratório (SDR) ou Doença da Membrana Hialina é comum em prematuros. Qual a função biofísica do surfactante que está ausente nesses casos?',
    alternativas: ['Aumentar a resistência das vias aéreas.', 'Reduzir a tensão superficial nos alvéolos, impedindo o colapso na expiração.', 'Estimular a produção de muco brônquico.', 'Facilitar a difusão de CO2 para o sangue.', 'Neutralizar o pH do líquido amniótico nos pulmões.'],
    gabarito: 1,
    comentario: `● Por que está certa: O surfactante (produzido pelos pneumócitos tipo II) quebra a coesão das moléculas de água na interface ar-líquido alveolar. Sem ele, a tensão superficial é tão alta que o alvéolo colapsa (atelectasia), exigindo um esforço respiratório exaustivo.`
  },
  {
    id: 'm7-p3-q6',
    number: 6,
    temaPrincipal: 'Anexos Embrionários',
    topicoEspecifico: 'Líquido Amniótico (Oligodrâmnio)',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'Um feto apresenta agenesia renal bilateral (Síndrome de Potter). Qual alteração no volume de líquido amniótico e qual consequência pulmonar são esperadas?',
    alternativas: ['Polidrâmnio; Edema pulmonar.', 'Oligodrâmnio; Hipoplasia pulmonar.', 'Volume normal; Pneumonia congênita.', 'Oligodrâmnio; Maturação pulmonar acelerada.', 'Polidrâmnio; Hérnia diafragmática.'],
    gabarito: 1,
    comentario: `● Por que está certa: A partir do 2º trimestre, a urina fetal é a principal fonte de líquido amniótico. Sem rins, há pouco líquido (oligodrâmnio). O líquido amniótico é essencial para a expansão mecânica dos pulmões; sem ele, os pulmões não se desenvolvem (hipoplasia).`
  },
  {
    id: 'm7-p3-q7',
    number: 7,
    temaPrincipal: 'Sistema Digestório',
    topicoEspecifico: 'Rotação do Intestino Médio',
    grauImportancia: 'Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'Durante a 10ª semana, o intestino retorna à cavidade abdominal realizando uma rotação. Qual o sentido e a graduação total dessa rotação em torno da artéria mesentérica superior?',
    alternativas: ['Horário; 90 graus.', 'Anti-horário; 270 graus.', 'Horário; 180 graus.', 'Anti-horário; 90 graus.', 'Não ocorre rotação, apenas retração.'],
    gabarito: 1,
    comentario: `● Por que está certa: O intestino médio sofre uma rotação total de 270° no sentido anti-horário. 90° ocorrem durante a herniação fisiológica e os outros 180° durante o retorno à cavidade abdominal.`
  },
  {
    id: 'm7-p3-q8',
    number: 8,
    temaPrincipal: 'Sistema Esquelético',
    topicoEspecifico: 'Ossificação Endocondral',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'A maioria dos ossos longos do corpo desenvolve-se através da ossificação endocondral. Esse processo caracteriza-se por:',
    alternativas: ['Formação direta do osso a partir do mesênquima.', 'Substituição de um molde de cartilagem hialina por tecido ósseo.', 'Crescimento exclusivo por aposição periosteal.', 'Ausência de centros de ossificação primários.', 'Ocorre apenas nos ossos do crânio.'],
    gabarito: 1,
    comentario: `● Por que está certa: Na ossificação endocondral, células mesenquimais formam primeiro um modelo de cartilagem, que depois é invadido por vasos e osteoblastos para ser substituído por osso. A ossificação intramembranosa (direta) ocorre nos ossos chatos do crânio.`
  },
  {
    id: 'm7-p3-q9',
    number: 9,
    temaPrincipal: 'Sistema Nervoso',
    topicoEspecifico: 'Fechamento do Tubo Neural',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'A suplementação periconcepcional com Ácido Fólico é recomendada mundialmente para prevenir quais tipos de malformações?',
    alternativas: ['Cardiopatias congênitas.', 'Defeitos do tubo neural (como anencefalia e espinha bífida).', 'Membros supranumerários.', 'Atresia esofágica.', 'Fenda palatina isolada.'],
    gabarito: 1,
    comentario: `● Por que está certa: O folato é essencial para a síntese de DNA e divisão celular rápida durante o fechamento das pregas neurais (que ocorre entre a 3ª e 4ª semana). Sua deficiência impede o fechamento completo do neuroporo cranial ou caudal.`
  },
  {
    id: 'm7-p3-q10',
    number: 10,
    temaPrincipal: 'Embriologia Geral',
    topicoEspecifico: 'Gastrulação',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'A gastrulação é o evento mais importante da terceira semana de desenvolvimento. Ela é definida como:',
    alternativas: ['O processo de implantação do blastocisto.', 'A formação do disco embrionário bilaminar.', 'O processo pelo qual as três camadas germinativas (ectoderma, mesoderma e endoderma) são estabelecidas.', 'O início da batida cardíaca fetal.', 'A formação da placenta definitiva.'],
    gabarito: 2,
    comentario: `● Por que está certa: Através da linha primitiva, células do epiblasto migram e invaginam para formar o endoderma e o mesoderma, enquanto as que permanecem no topo tornam-se o ectoderma.`
  },
  {
    id: 'm7-p3-q11',
    number: 11,
    temaPrincipal: 'Sistema Cardiovascular',
    topicoEspecifico: 'Circulação Fetal',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'Na circulação fetal, o sangue com maior teor de oxigénio chega ao feto pela veia umbilical. Qual estrutura permite que a maior parte deste sangue passe diretamente do átrio direito para o átrio esquerdo, desviando-se dos pulmões?',
    alternativas: ['Ducto arterioso.', 'Ducto venoso.', 'Forame oval.', 'Septo transverso.', 'Válvula aórtica.'],
    gabarito: 2,
    comentario: `● Por que está certa: O forame oval é uma abertura no septo interatrial que permite o shunt direita-esquerda, garantindo que o sangue oxigenado chegue ao ventrículo esquerdo e seja bombeado para o cérebro e tecidos sistémicos.`
  },
  {
    id: 'm7-p3-q12',
    number: 12,
    temaPrincipal: 'Sistema Urogenital',
    topicoEspecifico: 'Desenvolvimento Renal',
    grauImportancia: 'Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'O rim definitivo (metanefro) forma-se a partir da interação de duas estruturas mesodérmicas. Quais são elas?',
    alternativas: ['Pronefro e Mesonefro.', 'Brotamento ureteral e Blastema metanéfrico.', 'Ducto paramesonéfrico e Gónada.', 'Alantoide e Cloaca.', 'Crista neural e Mesoderma lateral.'],
    gabarito: 1,
    comentario: `● Por que está certa: O brotamento ureteral (origina ureter, pelve, cálices e ductos coletores) induz o blastema metanéfrico a formar os nefrónios. Sem essa interação mútua, o rim não se desenvolve.`
  },
  {
    id: 'm7-p3-q13',
    number: 13,
    temaPrincipal: 'Sistema Nervoso',
    topicoEspecifico: 'Vesículas Encefálicas',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'O Prosencéfalo divide-se em duas vesículas secundárias. Quais são elas e o que originam no adulto?',
    alternativas: ['Metencéfalo (Ponte) e Mielencéfalo (Bulbo).', 'Telencéfalo (Hemisférios cerebrais) e Diencéfalo (Tálamo/Hipotálamo).', 'Mesencéfalo (Mesencéfalo) e Rombencéfalo (Cerebelo).', 'Ectoderma e Neuroectoderma.', 'Medula espinhal e Nervos cranianos.'],
    gabarito: 1,
    comentario: `● Por que está certa: O telencéfalo expande-se para formar o córtex e núcleos da base, enquanto o diencéfalo forma as estruturas centrais de processamento e controle endócrino.`
  },
  {
    id: 'm7-p3-q14',
    number: 14,
    temaPrincipal: 'Sistema Respiratório',
    topicoEspecifico: 'Fístula Traqueoesofágica',
    grauImportancia: 'Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'A separação incompleta entre o divertículo respiratório e o esôfago pelo septo traqueoesofágico resulta em atresia de esôfago e fístulas. Qual o sinal clínico pré-natal comum nessa condição?',
    alternativas: ['Oligodrâmnio.', 'Polidrâmnio.', 'Crescimento intrauterino retardado.', 'Bradicardia fetal.', 'Hidropisia fetal.'],
    gabarito: 1,
    comentario: `● Por que está certa: O feto normalmente deglute líquido amniótico. Se houver atresia de esôfago, o líquido não chega ao estômago/intestino para ser absorvido, acumulando-se na cavidade amniótica (polidrâmnio).`
  },
  {
    id: 'm7-p3-q15',
    number: 15,
    temaPrincipal: 'Sistema Tegumentar',
    topicoEspecifico: 'Glândulas Mamárias',
    grauImportancia: 'Baixo',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'As glândulas mamárias são consideradas glândulas sudoríparas modificadas. Elas originam-se de qual camada germinativa?',
    alternativas: ['Endoderma.', 'Mesoderma paraxial.', 'Ectoderma (Cristas mamárias).', 'Mesoderma lateral.', 'Crista neural.'],
    gabarito: 2,
    comentario: `● Por que está certa: As glândulas mamárias desenvolvem-se a partir de espessamentos lineares do ectoderma (linhas ou cristas mamárias) que se estendem da axila à região inguinal.`
  },
  {
    id: 'm7-p3-q16',
    number: 16,
    temaPrincipal: 'Sistema Urogenital',
    topicoEspecifico: 'Diferenciação Sexual',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'No desenvolvimento masculino, qual hormona é responsável pela regressão dos ductos paramesonéfricos (Müller)?',
    alternativas: ['Testosterona.', 'Di-hidrotestosterona (DHT).', 'Substância Inibidora de Müller (AMH).', 'Estrogénio.', 'Progesterona.'],
    gabarito: 2,
    comentario: `● Por que está certa: As células de Sertoli produzem o AMH, que causa a involução dos ductos de Müller. A testosterona (células de Leydig) estimula o desenvolvimento dos ductos de Wolff (vias masculinas).`
  },
  {
    id: 'm7-p3-q17',
    number: 17,
    temaPrincipal: 'Sistema Cardiovascular',
    topicoEspecifico: 'Arcos Aórticos',
    grauImportancia: 'Médio',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'O quarto arco aórtico esquerdo contribui para a formação de qual estrutura vascular definitiva?',
    alternativas: ['Artéria pulmonar direita.', 'Parte do arco da aorta.', 'Artéria carótida comum.', 'Artéria subclávia direita.', 'Ducto arterioso.'],
    gabarito: 1,
    comentario: `● Por que está certa: O 4º arco esquerdo forma parte do arco aórtico. O 4º arco direito forma a parte proximal da artéria subclávia direita. O 6º arco esquerdo forma o ducto arterioso.`
  },
  {
    id: 'm7-p3-q18',
    number: 18,
    temaPrincipal: 'Sistema Nervoso',
    topicoEspecifico: 'Medula Espinhal',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'Na organização do tubo neural, a Placa Alar e a Placa Basal dão origem, respetivamente, a:',
    alternativas: ['Neurónios motores e Neurónios sensitivos.', 'Neurónios sensitivos e Neurónios motores.', 'Células da glia e Neurónios.', 'Substância branca e Substância cinzenta.', 'Encéfalo e Medula.'],
    gabarito: 1,
    comentario: `● Por que está certa: A placa alar (dorsal) diferencia-se em áreas sensitivas. A placa basal (ventral) diferencia-se em áreas motoras. Essa organização mantém-se na medula espinhal adulta.`
  },
  {
    id: 'm7-p3-q19',
    number: 19,
    temaPrincipal: 'Sistema Digestório',
    topicoEspecifico: 'Desenvolvimento do Pâncreas',
    grauImportancia: 'Médio',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'O pâncreas forma-se a partir da fusão de dois brotos (ventral e dorsal). Qual estrutura é formada exclusivamente pelo broto ventral?',
    alternativas: ['Cauda do pâncreas.', 'Corpo do pâncreas.', 'Processo uncinado e parte inferior da cabeça.', 'Ducto pancreático acessório.', 'Ilhotas de Langerhans.'],
    gabarito: 2,
    comentario: `● Por que está certa: O broto ventral gira em torno do duodeno para se fundir com o broto dorsal. Ele contribui com o processo uncinado e a parte inferior da cabeça do pâncreas.`
  },
  {
    id: 'm7-p3-q20',
    number: 20,
    temaPrincipal: 'Embriologia Geral',
    topicoEspecifico: 'Segunda Semana',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'A segunda semana de desenvolvimento é conhecida como a "semana dos pares". Qual das alternativas abaixo NÃO representa um par formado nessa fase?',
    alternativas: ['Trofo-blasto (Citotrofoblasto e Sinciciotrofoblasto).', 'Embrioblasto (Epiblasto e Hipoblasto).', 'Cavidades (Amniótica e Saco Vitelino).', 'Camadas Germinativas (Ectoderma e Mesoderma).', 'Mesoderma Extraembrionário (Somático e Esplâncnico).'],
    gabarito: 3,
    comentario: `● Por que está certa: As camadas germinativas (ectoderma, mesoderma e endoderma) formam um trio e só surgem na terceira semana (gastrulação). Na segunda semana, o disco é bilaminar (epiblasto e hipoblasto).`
  },
  {
    id: 'm7-p3-q21',
    number: 21,
    temaPrincipal: 'Anexos Embrionários',
    topicoEspecifico: 'Placenta',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'A barreira placentária separa o sangue materno do fetal. No final da gestação, ela é composta por quais camadas?',
    alternativas: ['Sinciciotrofoblasto e Endotélio capilar fetal apenas.', 'Citotrofoblasto, Sinciciotrofoblasto, Mesoderma e Endotélio.', 'Apenas Sinciciotrofoblasto.', 'Parede uterina e Âmnio.', 'Sangue materno e Sangue fetal misturados.'],
    gabarito: 0,
    comentario: `● Por que está certa: Com o avanço da gestação, a barreira torna-se mais fina para facilitar as trocas. O citotrofoblasto e o tecido conjuntivo desaparecem em muitas áreas, deixando apenas o sincício e o endotélio capilar.`
  },
  {
    id: 'm7-p3-q22',
    number: 22,
    temaPrincipal: 'Sistema Cardiovascular',
    topicoEspecifico: 'Desenvolvimento do Coração',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'O septo interatrial definitivo é formado pela fusão de dois septos. Qual deles possui uma abertura chamada forame oval?',
    alternativas: ['Septum primum.', 'Septum secundum.', 'Septum transversum.', 'Almofada endocárdica.', 'Septo aórtico-pulmonar.'],
    gabarito: 1,
    comentario: `● Por que está certa: O septum secundum cresce à direita do primum e não se fecha completamente, deixando o forame oval. O septum primum funciona como uma válvula para esse forame.`
  },
  {
    id: 'm7-p3-q23',
    number: 23,
    temaPrincipal: 'Sistema Respiratório',
    topicoEspecifico: 'Maturação Pulmonar',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'A produção de surfactante começa a ser significativa a partir de qual período do desenvolvimento pulmonar?',
    alternativas: ['Fase Pseudoglandular.', 'Fase Canalicular (final).', 'Fase Sacular.', 'Fase Alveolar.', 'Somente após o nascimento.'],
    gabarito: 1,
    comentario: `● Por que está certa: No final da fase canalicular (por volta da 24ª-26ª semana), os pneumócitos tipo II começam a produzir surfactante, permitindo a sobrevivência de prematuros extremos.`
  },
  {
    id: 'm7-p3-q24',
    number: 24,
    temaPrincipal: 'Sistema Digestório',
    topicoEspecifico: 'Hérnia Umbilical Fisiológica',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'A hérnia umbilical fisiológica ocorre porque:',
    alternativas: ['A parede abdominal não se fecha.', 'O fígado e os rins crescem rapidamente, reduzindo o espaço na cavidade abdominal.', 'O feto deglute muito líquido amniótico.', 'Há uma falha na rotação do estômago.', 'O cordão umbilical é muito curto.'],
    gabarito: 1,
    comentario: `● Por que está certa: Durante a 6ª semana, o rápido crescimento do fígado e das alças intestinais "expulsa" o intestino para o cordão umbilical. O intestino retorna à cavidade na 10ª semana.`
  },
  {
    id: 'm7-p3-q25',
    number: 25,
    temaPrincipal: 'Sistema Nervoso',
    topicoEspecifico: 'Cristas Neurais',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'As células da crista neural são chamadas de "quarta camada germinativa" devido à sua versatilidade. Qual das estruturas abaixo NÃO deriva da crista neural?',
    alternativas: ['Melanócitos.', 'Gânglios sensitivos e autonómicos.', 'Medula da glândula suprarrenal.', 'Células de Schwann.', 'Epitélio do trato digestório.'],
    gabarito: 4,
    comentario: `● Por que está certa: O epitélio do trato digestório deriva do endoderma. A crista neural contribui para o sistema nervoso entérico (plexos), mas não para o revestimento epitelial.`
  },
  {
    id: 'm7-p3-q26',
    number: 26,
    temaPrincipal: 'Sistema Cardiovascular',
    topicoEspecifico: 'Veias Embrionárias',
    grauImportancia: 'Baixo',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'O sistema venoso embrionário é composto por três pares de veias principais. Quais são elas?',
    alternativas: ['Veias Umbilicais, Vitelinas e Cardinais.', 'Veias Cavas, Pulmonares e Renais.', 'Veias Porta, Hepática e Esplénica.', 'Veias Jugulares, Subclávias e Ilíacas.', 'Veias Aorta, Pulmonar e Ázigos.'],
    gabarito: 0,
    comentario: `● Por que está certa: Vitelinas (do saco vitelino), Umbilicais (da placenta) e Cardinais (do corpo do embrião). Elas drenam para o seio venoso do coração primitivo.`
  },
  {
    id: 'm7-p3-q27',
    number: 27,
    temaPrincipal: 'Sistema Esquelético',
    topicoEspecifico: 'Desenvolvimento das Vértebras',
    grauImportancia: 'Médio',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'As vértebras formam-se a partir de qual estrutura mesodérmica?',
    alternativas: ['Mesoderma lateral.', 'Esclerótomo (parte do somito).', 'Dermátomo.', 'Miótomo.', 'Notocorda.'],
    gabarito: 1,
    comentario: `● Por que está certa: O somito divide-se em esclerótomo (osso/cartilagem), miótomo (músculo) e dermátomo (derme). A notocorda induz a formação, mas desaparece, restando apenas como o núcleo pulposo do disco intervertebral.`
  },
  {
    id: 'm7-p3-q28',
    number: 28,
    temaPrincipal: 'Sistema Muscular',
    topicoEspecifico: 'Músculo Esquelético',
    grauImportancia: 'Baixo',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'A musculatura esquelética dos membros deriva de qual fonte?',
    alternativas: ['Mesoderma lateral esplâncnico.', 'Mesoderma paraxial (somitos).', 'Ectoderma.', 'Endoderma.', 'Crista neural.'],
    gabarito: 1,
    comentario: `● Por que está certa: Células do miótomo dos somitos migram para os brotos dos membros para formar os músculos extensores e flexores.`
  },
  {
    id: 'm7-p3-q29',
    number: 29,
    temaPrincipal: 'Membros',
    topicoEspecifico: 'Eixo Proximodistal',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'O crescimento proximodistal dos membros é controlado por qual estrutura sinalizadora?',
    alternativas: ['Zona de Atividade Polarizada (ZPA).', 'Crista Ectodérmica Apical (CEA).', 'Mesoderma paraxial.', 'Notocorda.', 'Placa neural.'],
    gabarito: 1,
    comentario: `● Por que está certa: A CEA (na ponta do broto do membro) mantém o mesoderma subjacente indiferenciado e em rápida proliferação. Se a CEA for removida, o crescimento do membro para.`
  },
  {
    id: 'm7-p3-q30',
    number: 30,
    temaPrincipal: 'Face e Pescoço',
    topicoEspecifico: 'Arcos Faríngeos',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'O primeiro arco faríngeo (arco mandibular) dá origem a quais estruturas?',
    alternativas: ['Músculos da expressão facial e estribo.', 'Mandíbula, maxila, martelo e bigorna.', 'Cartilagem tireoide e epiglote.', 'Timo e glândulas paratireoides.', 'Língua e amígdalas apenas.'],
    gabarito: 1,
    comentario: `● Por que está certa: O 1º arco forma os ossos da face e os ossículos do ouvido médio (martelo/bigorna). O 2º arco (arco hioide) forma o estribo e os músculos da expressão facial.`
  },
  {
    id: 'm7-p3-q31',
    number: 31,
    temaPrincipal: 'Face e Pescoço',
    topicoEspecifico: 'Bolsas Faríngeas',
    grauImportancia: 'Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'A terceira bolsa faríngea é responsável pela formação de quais órgãos?',
    alternativas: ['Ouvido médio e tuba auditiva.', 'Amígdala palatina.', 'Glândula paratireoide inferior e Timo.', 'Glândula paratireoide superior.', 'Glândula tireoide.'],
    gabarito: 2,
    comentario: `● Por que está certa: Curiosamente, a paratireoide inferior (3ª bolsa) migra com o timo e acaba ficando abaixo da paratireoide superior (4ª bolsa).`
  },
  {
    id: 'm7-p3-q32',
    number: 32,
    temaPrincipal: 'Face e Pescoço',
    topicoEspecifico: 'Desenvolvimento da Face',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'O lábio leporino (fenda labial) ocorre devido à falha na fusão de quais processos?',
    alternativas: ['Processos palatinos laterais.', 'Processo maxilar e processo nasal medial.', 'Processos mandibulares.', 'Processo frontal e processo maxilar.', 'Processos nasais laterais.'],
    gabarito: 1,
    comentario: `● Por que está certa: A fenda labial resulta da falta de fusão entre o segmento intermaxilar (nasais mediais) e o processo maxilar. A fenda palatina é a falha entre as prateleiras palatinas.`
  },
  {
    id: 'm7-p3-q33',
    number: 33,
    temaPrincipal: 'Face e Pescoço',
    topicoEspecifico: 'Glândula Tireoide',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'A glândula tireoide origina-se na base da língua e migra para o pescoço. Qual estrutura marca o local de origem e o caminho dessa migração?',
    alternativas: ['Forame cego e Ducto tireoglosso.', 'Seio cervical.', 'Primeira fenda faríngea.', 'Ducto auditivo.', 'Istmo da tireoide.'],
    gabarito: 0,
    comentario: `● Por que está certa: O forame cego na língua é o ponto de partida. O ducto tireoglosso é o canal que normalmente desaparece; se persistir, pode formar cistos tireoglossos no pescoço.`
  },
  {
    id: 'm7-p3-q34',
    number: 34,
    temaPrincipal: 'Órgãos dos Sentidos',
    topicoEspecifico: 'Desenvolvimento do Olho',
    grauImportancia: 'Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'A retina origina-se de qual estrutura?',
    alternativas: ['Ectoderma de superfície.', 'Cálice ótico (neuroectoderma).', 'Mesoderma lateral.', 'Crista neural.', 'Endoderma.'],
    gabarito: 1,
    comentario: `● Por que está certa: O cálice ótico é uma evaginação do diencéfalo. O ectoderma de superfície forma o cristalino e a córnea externa.`
  },
  {
    id: 'm7-p3-q35',
    number: 35,
    temaPrincipal: 'Órgãos dos Sentidos',
    topicoEspecifico: 'Desenvolvimento do Ouvido',
    grauImportancia: 'Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'O ouvido interno (cóclea e canais semicirculares) desenvolve-se a partir de:',
    alternativas: ['Primeira bolsa faríngea.', 'Placódio ótico (ectoderma).', 'Primeiro arco faríngeo.', 'Crista neural.', 'Mesoderma paraxial.'],
    gabarito: 1,
    comentario: `● Por que está certa: O placódio ótico invagina para formar a vesícula ótica (otocisto), que se diferencia nas estruturas membranosas do ouvido interno.`
  },
  {
    id: 'm7-p3-q36',
    number: 36,
    temaPrincipal: 'Embriologia Geral',
    topicoEspecifico: 'Primeira Semana',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'A zona pelúcida é fundamental para evitar qual evento indesejado na primeira semana?',
    alternativas: ['A fecundação por mais de um espermatozoide.', 'A implantação prematura (gravidez ectópica tubária).', 'A formação do blastocisto.', 'A morte do zigoto.', 'A divisão celular (clivagem).'],
    gabarito: 1,
    comentario: `● Por que está certa: A zona pelúcida envolve o embrião até que ele chegue ao útero. Se ela se romper na trompa, o embrião pode implantar ali mesmo, gerando uma gravidez ectópica.`
  },
  {
    id: 'm7-p3-q37',
    number: 37,
    temaPrincipal: 'Embriologia Geral',
    topicoEspecifico: 'Teratologia',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'Qual o período de maior sensibilidade do embrião à indução de malformações congênitas estruturais por agentes teratógenos?',
    alternativas: ['Primeira e segunda semanas (período pré-embrionário).', 'Terceira à oitava semanas (período embrionário/organogénese).', 'Nona semana ao nascimento (período fetal).', 'Somente no momento do parto.', 'Durante todo o período fértil da mulher.'],
    gabarito: 1,
    comentario: `● Por que está certa: É durante a organogénese que os esboços dos órgãos estão sendo formados. Antes disso (1ª-2ª sem), o efeito costuma ser "tudo ou nada" (morte ou recuperação total). Depois (período fetal), os danos costumam ser funcionais ou de crescimento.`
  },
  {
    id: 'm7-p3-q38',
    number: 38,
    temaPrincipal: 'Sistema Cardiovascular',
    topicoEspecifico: 'Septação do Tronco Arterial',
    grauImportancia: 'Muito Alto',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'A Transposição dos Grandes Vasos ocorre devido a uma falha em qual processo embriológico?',
    alternativas: ['Fechamento do forame oval.', 'Formação em espiral do septo aórtico-pulmonar.', 'Desenvolvimento do ventrículo esquerdo.', 'Involução do ducto arterioso.', 'Fusão das almofadas endocárdicas.'],
    gabarito: 1,
    comentario: `● Por que está certa: O septo que divide a aorta da artéria pulmonar deve crescer em espiral. Se ele crescer reto, a aorta sai do ventrículo direito e a pulmonar do esquerdo.`
  },
  {
    id: 'm7-p3-q39',
    number: 39,
    temaPrincipal: 'Sistema Digestório',
    topicoEspecifico: 'Desenvolvimento do Fígado',
    grauImportancia: 'Baixo',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'O parênquima hepático (hepatócitos) e o revestimento das vias biliares derivam de qual camada?',
    alternativas: ['Ectoderma.', 'Mesoderma lateral.', 'Endoderma (Divertículo hepático).', 'Crista neural.', 'Mesoderma paraxial.'],
    gabarito: 2,
    comentario: `● Por que está certa: O fígado surge como uma evaginação do endoderma do intestino anterior. O tecido conjuntivo e os vasos do fígado derivam do mesoderma.`
  },
  {
    id: 'm7-p3-q40',
    number: 40,
    temaPrincipal: 'Sistema Urogenital',
    topicoEspecifico: 'Cloaca',
    grauImportancia: 'Médio',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'O septo urorretal divide a cloaca em duas partes. Quais são elas?',
    alternativas: ['Bexiga e Uretra.', 'Seio urogenital (anterior) e Canal anal (posterior).', 'Reto e Cólon.', 'Ureter e Pelve renal.', 'Vagina e Útero.'],
    gabarito: 1,
    comentario: `● Por que está certa: O septo cresce em direção à membrana cloacal, separando as vias urinárias/genitais da via digestória final.`
  },
  {
    id: 'm7-p3-q41',
    number: 41,
    temaPrincipal: 'Sistema Muscular',
    topicoEspecifico: 'Músculo Cardíaco',
    grauImportancia: 'Baixo',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'O músculo cardíaco desenvolve-se a partir de:',
    alternativas: ['Mesoderma paraxial.', 'Mesoderma lateral esplâncnico (que envolve o tubo cardíaco).', 'Ectoderma.', 'Crista neural.', 'Endoderma.'],
    gabarito: 1,
    comentario: `● Por que está certa: O mesoderma esplâncnico que envolve o tubo cardíaco endotelial diferencia-se em miocárdio.`
  },
  {
    id: 'm7-p3-q42',
    number: 42,
    temaPrincipal: 'Membros',
    topicoEspecifico: 'Apoptose e Dedos',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟢 Fácil',
    enunciado: 'A formação dos dedos das mãos e dos pés depende de qual processo celular nas regiões interdigitais?',
    alternativas: ['Proliferação celular acelerada.', 'Apoptose (morte celular programada).', 'Diferenciação em cartilagem.', 'Migração de células da crista neural.', 'Fusão de pequenos ossos.'],
    gabarito: 1,
    comentario: `● Por que está certa: Inicialmente, as mãos e pés são como "remos". A morte programada das células entre os dedos permite a separação dos mesmos. A falha nesse processo gera a sindactilia (dedos colados).`
  },
  {
    id: 'm7-p3-q43',
    number: 43,
    temaPrincipal: 'Face e Pescoço',
    topicoEspecifico: 'Língua',
    grauImportancia: 'Baixo',
    nivelDificuldade: '🔴 Difícil',
    enunciado: 'A musculatura da língua tem uma origem embriológica curiosa. Qual é ela?',
    alternativas: ['Arcos faríngeos.', 'Miótomos occipitais (migram para a face).', 'Endoderma da boca.', 'Crista neural.', 'Mesoderma lateral.'],
    gabarito: 1,
    comentario: `● Por que está certa: Embora o revestimento da língua venha dos arcos faríngeos, os seus músculos vêm de somitos da região da nuca (occipitais) que migram para a cavidade oral.`
  },
  {
    id: 'm7-p3-q44',
    number: 44,
    temaPrincipal: 'Órgãos dos Sentidos',
    topicoEspecifico: 'Ouvido Médio',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'A cavidade do ouvido médio e a tuba auditiva derivam de qual estrutura?',
    alternativas: ['Primeira fenda faríngea.', 'Primeira bolsa faríngea.', 'Segundo arco faríngeo.', 'Crista neural.', 'Ectoderma de superfície.'],
    gabarito: 1,
    comentario: `● Por que está certa: A 1ª bolsa expande-se para formar o recesso tubotimpânico. A 1ª fenda (ectoderma) forma o conduto auditivo externo.`
  },
  {
    id: 'm7-p3-q45',
    number: 45,
    temaPrincipal: 'Embriologia Geral',
    topicoEspecifico: 'Notocorda',
    grauImportancia: 'Alto',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'Qual a principal função indutora da notocorda no início da terceira semana?',
    alternativas: ['Formar o coração.', 'Induzir o ectoderma subjacente a diferenciar-se em placa neural (neuroectoderma).', 'Formar o trato digestório.', 'Produzir células sanguíneas.', 'Estimular a formação dos membros.'],
    gabarito: 1,
    comentario: `● Por que está certa: A notocorda atua como o organizador central, enviando sinais químicos que dizem ao ectoderma para deixar de ser pele e tornar-se sistema nervoso.`
  },
  {
    id: 'm7-p3-q46',
    number: 46,
    temaPrincipal: 'Embriologia Geral',
    topicoEspecifico: 'Hatching (Eclosão)',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'O processo de "Hatching" ou eclosão do blastocisto consiste em:',
    alternativas: ['A saída do espermatozoide da zona pelúcida.', 'A saída do blastocisto de dentro da zona pelúcida para permitir a implantação.', 'A ruptura do folículo ovariano.', 'A descida do zigoto pela trompa.', 'A formação da cavidade blastocística.'],
    gabarito: 1,
    comentario: `● Por que está certa: O embrião chega ao útero dentro da zona pelúcida. Para implantar, ele precisa "nascer" dela (hatching), caso contrário, o trofoblasto não consegue contactar o epitélio endometrial.`
  },
  {
    id: 'm7-p3-q47',
    number: 47,
    temaPrincipal: 'Desenvolvimento Embrionário',
    topicoEspecifico: 'Clivagem e Totipotência',
    grauImportancia: 'Médio',
    nivelDificuldade: '🟡 Médio',
    enunciado: 'Durante as divisões de clivagem, as células resultantes são chamadas de blastómeros. Até qual estágio celular considera-se que os blastómeros humanos mantêm a totipotência (capacidade de formar um organismo completo e anexos)?',
    alternativas: ['Zigoto apenas.', 'Estágio de 2 a 8 células.', 'Blastocisto expandido.', 'Gástrula.', 'Somente após a formação da linha primitiva.'],
    gabarito: 1,
    comentario: `● Por que está certa: Após o estágio de 8 células, as células sofrem "compactação" e iniciam a diferenciação em trofoblasto ou MCI, perdendo a totipotência e tornando-se pluripotentes.`
  }
];
